services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/conf/generate_config.sh:/etc/nginx/conf.d/generate_config.sh:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/letsencrypt:/var/www/letsencrypt:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot-path:/var/www/html
    depends_on:
      - web
    restart: always
    networks:
      - odoo_network
    environment:
      - ODOO_HOST=web
      - ODOO_PORT=${ODOO_PORT:-8069}
      - ODOO_CHAT_PORT=${ODOO_CHAT_PORT:-8072}
      - NGINX_PORT=${NGINX_PORT:-80}
      - SERVER_NAME=${SERVER_NAME:-localhost}
    command: >
      /bin/bash -c "cd /etc/nginx/conf.d && 
      chmod +x generate_config.sh &&
      ./generate_config.sh --odoo-host $$ODOO_HOST --odoo-port $$ODOO_PORT 
      --chat-port $$ODOO_CHAT_PORT --nginx-port $$NGINX_PORT 
      --server-name $$SERVER_NAME && nginx -g 'daemon off;'"

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "${ODOO_PORT:-8069}:8069"
      - "${ODOO_CHAT_PORT:-8072}:8072"
    volumes:
      - odoo-web-data:/odoo-server
      - ./config:/etc/odoo:ro
      - ./logs:/var/log/odoo
      - ./addons:/mnt/extra-addons:ro
      - ./backups:/mnt/backups
      - ./moxogo18:/mnt/moxogo18:ro
      - odoo-sessions:/mnt/.local
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      #- DB_USER=${DB_USER:-odoo}
      #- DB_PASSWORD=${POSTGRES_PASSWORD}
      #- DB_NAME=${DB_NAME:-postgres}
      - DB_USER=odoo
      - DB_PASSWORD=odoo123
      - DB_NAME=postgres
      - PROXY_MODE=True
      - LONGPOLLING_PORT=${ODOO_CHAT_PORT:-8072}
      - WEB_SOCKET=True
    user: odoo
    restart: always
    networks:
      - odoo_network

  db:
    image: postgres:17
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      #- POSTGRES_DB=${DB_NAME:-postgres}
      #- POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      #- POSTGRES_USER=${DB_USER:-odoo}
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo123
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: postgres -c 'hba_file=/etc/postgresql/pg_hba.conf'
    restart: always
    networks:
      - odoo_network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot-path:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN}

volumes:
  odoo-web-data:
  odoo-db-data:
  nginx-web-data:
  certbot-etc:
  certbot-var:
  webroot-path:
  odoo-sessions:

networks:
  odoo_network:
    driver: bridge
