version: '3.8'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/letsencrypt:/etc/letsencrypt:ro
      - certbot-webroot:/var/www/html
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - ENABLE_SSL=${ENABLE_SSL:-false}
      - ODOO_PORT=${ODOO_PORT:-8069}
      - ODOO_CHAT_PORT=${ODOO_CHAT_PORT:-8072}
    depends_on:
      - web
    command: >
      /bin/sh -c "
      if [ \"$${ENABLE_SSL}\" = \"true\" ]; then
        envsubst '$$DOMAIN $$ODOO_PORT $$ODOO_CHAT_PORT' < /etc/nginx/conf.d/ssl.conf > /etc/nginx/conf.d/default.conf;
      else
        envsubst '$$DOMAIN $$ODOO_PORT $$ODOO_CHAT_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf;
      fi
      && nginx -g 'daemon off;'"
    networks:
      - odoo_network

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: odoo:18.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${ODOO_PORT:-8069}:8069"
      - "${ODOO_CHAT_PORT:-8072}:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./logs:/var/log/odoo
      - ./addons:/mnt/extra-addons
      - type: bind
        source: ./moxogo18
        target: /mnt/extra-addons/moxogo18
        read_only: true
        consistency: cached
      - ./backups:/mnt/backups
      - odoo-sessions:/mnt/.local
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-odoo}
      - POSTGRES_USER=${POSTGRES_USER:-odoo}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-odoo}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - ODOO_PORT=${ODOO_PORT:-8069}
      - ODOO_CHAT_PORT=${ODOO_CHAT_PORT:-8072}
    command: ["--config=/etc/odoo/odoo.conf"]
    user: odoo
    restart: always
    networks:
      - odoo_network

  db:
    image: postgres:15
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-odoo}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-odoo}
      - POSTGRES_USER=${POSTGRES_USER:-odoo}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: postgres -c 'hba_file=/etc/postgresql/pg_hba.conf'
    restart: unless-stopped
    networks:
      - odoo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-odoo}"]
      interval: 10s
      timeout: 5s
      retries: 5

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN}

volumes:
  odoo-web-data:
  odoo-db-data:
  certbot-webroot:
  odoo-sessions:

networks:
  odoo_network:
    driver: bridge
