version: '3.1'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/letsencrypt:/var/www/letsencrypt:ro
    depends_on:
      - web
    restart: always
    networks:
      - odoo_network

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/odoo-server
      - ./config:/etc/odoo
      - ./logs:/var/log/odoo
      - ./addons:/mnt/extra-addons
      - ./moxogo18:/mnt/moxogo18
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${POSTGRES_PASSWORD}
      - PROXY_MODE=True
      - LONGPOLLING_PORT=8072
      - WEB_SOCKET=True
    restart: always
    networks:
      - odoo_network

  db:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - odoo_network

volumes:
  odoo-web-data:
  odoo-db-data:
  nginx-web-data:

networks:
  odoo_network:
    driver: bridge
